# Generated by Django 6.0 on 2025-12-25 15:58

import core.utils
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('token', models.CharField(max_length=150, unique=True, verbose_name='Token')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('expires_at', models.DateTimeField(verbose_name='Expires at')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is used')),
            ],
            options={
                'verbose_name': 'Verification Token',
                'verbose_name_plural': 'Verification Tokens',
                'db_table': 'verification_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('name', models.CharField(blank=True, help_text='User display name (default: username)', max_length=100, null=True, verbose_name='Display name')),
                ('name_fa', models.CharField(blank=True, help_text='User display name (default: username)', max_length=100, null=True, verbose_name='Display name')),
                ('name_en', models.CharField(blank=True, help_text='User display name (default: username)', max_length=100, null=True, verbose_name='Display name')),
                ('role', models.CharField(choices=[('user', 'User'), ('teacher', 'Teacher'), ('admin', 'Admin')], default='user', help_text='User: Regular user, Teacher: Teacher, Admin: Administrator', max_length=20, verbose_name='User role')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Phone number')),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Phone verified at')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Email verified at')),
                ('profile_photo_path', models.ImageField(blank=True, null=True, upload_to=core.utils.upload_to_dynamic, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])], verbose_name='Profile photo')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('bio_fa', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('bio_en', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('custom', 'Custom'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True, verbose_name='Gender')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth date')),
                ('is_teacher_verified', models.BooleanField(default=False, help_text='Whether this teacher is verified by admin', verbose_name='Teacher verified')),
                ('teacher_verification_requested_at', models.DateTimeField(blank=True, null=True, verbose_name='Teacher verification requested at')),
                ('commission_rate_override', models.DecimalField(blank=True, decimal_places=2, help_text='Special commission rate for this teacher (if empty, default rate is used). Number between 0 and 100', max_digits=5, null=True, verbose_name='Special commission rate')),
                ('push_token', models.TextField(blank=True, help_text='Push notification token', null=True)),
                ('last_seen', models.DateTimeField(blank=True, help_text='Last online time', null=True, verbose_name='Last seen')),
                ('is_online', models.BooleanField(default=False, help_text='Online status', verbose_name='Is online')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='RegularUserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User Management',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.user',),
        ),
        migrations.CreateModel(
            name='TeacherUserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teacher Management',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.user',),
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('code', models.CharField(help_text='Hashed OTP code', max_length=100, verbose_name='Hashed code')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('expires_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Expires at')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is used')),
                ('purpose', models.CharField(choices=[('registration', 'Registration'), ('phone_verification', 'Phone Verification'), ('email_verification', 'Email Verification'), ('password_reset', 'Password Reset'), ('login', 'Login')], default='login', max_length=50, verbose_name='Purpose')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'OTP Code',
                'verbose_name_plural': 'OTP Codes',
                'db_table': 'otp_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='users_phone_af6883_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_teacher_verified'], name='users_is_teac_cd8c37_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['user', 'is_used', 'expires_at'], name='otp_codes_user_id_598e00_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['phone', 'code'], name='otp_codes_phone_d29639_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['email', 'code'], name='otp_codes_email_a86f0d_idx'),
        ),
    ]
