# Generated by Django 6.0 on 2025-12-26 09:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('image', models.ImageField(upload_to='avatars/templates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='Avatar image')),
            ],
            options={
                'verbose_name': 'Avatar Template',
                'verbose_name_plural': 'Avatar Templates',
                'db_table': 'avatar_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='selected_avatar',
            field=models.ForeignKey(blank=True, help_text='Avatar template selected by user', null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.avatartemplate', verbose_name='Selected avatar'),
        ),
    ]
