# Generated by Django 6.0 on 2025-12-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_avatartemplate_user_selected_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='available_times',
            field=models.JSONField(blank=True, help_text='JSON object with available teaching times', null=True, verbose_name='Available times'),
        ),
        migrations.AddField(
            model_name='user',
            name='experience_years',
            field=models.IntegerField(blank=True, help_text='Number of years of teaching experience', null=True, verbose_name='Years of experience'),
        ),
        migrations.AddField(
            model_name='user',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Suggested hourly teaching rate in default currency', max_digits=10, null=True, verbose_name='Hourly rate'),
        ),
        migrations.AddField(
            model_name='user',
            name='introduction_video',
            field=models.URLField(blank=True, help_text='YouTube or video URL for teacher introduction', null=True, verbose_name='Introduction video URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='languages_taught',
            field=models.CharField(blank=True, help_text='Languages that can be taught (comma-separated or JSON)', max_length=500, null=True, verbose_name='Languages taught'),
        ),
        migrations.AddField(
            model_name='user',
            name='qualifications',
            field=models.TextField(blank=True, help_text='Degrees, certifications, and professional qualifications', null=True, verbose_name='Educational qualifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='resume_summary',
            field=models.TextField(blank=True, help_text='Brief summary of professional experience and background', null=True, verbose_name='Resume summary'),
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, help_text='Area of specialization or expertise', max_length=500, null=True, verbose_name='Specialization'),
        ),
    ]
