# Generated by Django 6.0 on 2025-12-26 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_available_times_user_experience_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.CharField(blank=True, help_text='Birth date in Jalali calendar format (YYYY-MM-DD), e.g., 1403-05-24', max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='invalid_jalali_date', message='Birth date must be in YYYY-MM-DD format (Jalali calendar)', regex='^\\d{4}-\\d{2}-\\d{2}$')], verbose_name='Birth date'),
        ),
    ]
