# Generated by Django 6.0 on 2025-12-30 11:45

import core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatartemplate',
            name='image',
            field=models.ImageField(upload_to=core.utils.upload_to_dynamic, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='Avatar image'),
        ),
    ]
