# Generated by Django 6.0 on 2025-12-30 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_avatartemplate_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('parent_name', models.CharField(help_text='نام کامل والد', max_length=200, verbose_name='Parent full name')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('parent_password_hash', models.CharField(help_text='Hashed password for parent portal login', max_length=255, verbose_name='Parent password (hashed)')),
                ('can_view_class_history', models.BooleanField(default=True, help_text='آیا والد می\u200cتواند تاریخچه کلاس\u200cها را مشاهده کند؟', verbose_name='Can view class history')),
                ('can_view_payments', models.BooleanField(default=True, help_text='آیا والد می\u200cتواند پرداخت\u200cها را مشاهده کند؟', verbose_name='Can view payments')),
                ('can_select_teacher', models.BooleanField(default=False, help_text='آیا والد می\u200cتواند معلم برای کودک انتخاب کند؟', verbose_name='Can select teacher')),
                ('can_set_usage_time', models.BooleanField(default=True, help_text='آیا والد می\u200cتواند محدودیت زمان استفاده اپلیکیشن را تنظیم کند؟', verbose_name='Can set app usage time')),
                ('daily_usage_limit_minutes', models.IntegerField(blank=True, help_text='حداکثر دقایق استفاده روزانه از اپلیکیشن', null=True, verbose_name='Daily usage limit (minutes)')),
                ('allowed_start_time', models.TimeField(blank=True, help_text='ساعت شروع مجاز استفاده (مثال: 08:00)', null=True, verbose_name='Allowed start time')),
                ('allowed_end_time', models.TimeField(blank=True, help_text='ساعت پایان مجاز استفاده (مثال: 22:00)', null=True, verbose_name='Allowed end time')),
                ('is_active', models.BooleanField(default=True, help_text='آیا دسترسی والد فعال است؟', verbose_name='Is active')),
                ('last_login_at', models.DateTimeField(blank=True, help_text='آخرین بار ورود والد', null=True, verbose_name='Last login at')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'user'}, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Parent Profile',
                'verbose_name_plural': 'Parent Profiles',
                'db_table': 'parent_profiles',
                'ordering': ['student', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentAppUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('date', models.DateField(help_text='تاریخ استفاده', verbose_name='Date')),
                ('total_minutes', models.IntegerField(default=0, help_text='کل دقایق استفاده در این روز', verbose_name='Total minutes used')),
                ('session_count', models.IntegerField(default=0, help_text='تعداد جلسات استفاده در این روز', verbose_name='Number of sessions')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='account.parentprofile', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Parent App Usage Log',
                'verbose_name_plural': 'Parent App Usage Logs',
                'db_table': 'parent_app_usage_logs',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='parentprofile',
            index=models.Index(fields=['student'], name='parent_prof_student_1a2cca_idx'),
        ),
        migrations.AddIndex(
            model_name='parentprofile',
            index=models.Index(fields=['is_active'], name='parent_prof_is_acti_835c22_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parentprofile',
            unique_together={('student', 'parent_name')},
        ),
        migrations.AddIndex(
            model_name='parentappusagelog',
            index=models.Index(fields=['parent', '-date'], name='parent_app__parent__1ed3b3_idx'),
        ),
        migrations.AddIndex(
            model_name='parentappusagelog',
            index=models.Index(fields=['date'], name='parent_app__date_505eba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parentappusagelog',
            unique_together={('parent', 'date')},
        ),
    ]
