# Generated by Django 6.0 on 2025-12-31 06:01

import core.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_parentprofile_parentappusagelog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introduction_video',
            field=models.FileField(blank=True, help_text='Video file for teacher introduction (MP4, AVI, MOV, WebM, FLV, MKV, 3GP, M4V, OGV)', null=True, upload_to=core.utils.upload_to_dynamic, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'webm', 'flv', 'mkv', '3gp', 'm4v', 'ogv'])], verbose_name='Introduction video'),
        ),
    ]
