# Generated by Django 6.0 on 2025-12-31 15:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_introduction_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('rater_type', models.CharField(choices=[('student', 'Student'), ('parent', 'Parent')], default='student', help_text='نوع فردی که امتیاز می\u200cدهد', max_length=20, verbose_name='Rater Type')),
                ('stars', models.IntegerField(default=5, help_text='ستاره (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Stars')),
                ('comment', models.TextField(blank=True, help_text='نظر و بازخورد در مورد معلم', null=True, verbose_name='Comment')),
                ('is_anonymous', models.BooleanField(default=False, help_text='آیا نام ارائه\u200cدهنده نمایش داده شود؟', verbose_name='Is Anonymous')),
                ('is_verified', models.BooleanField(default=True, help_text='آیا این امتیاز تایید شده است؟', verbose_name='Is Verified')),
                ('rater', models.ForeignKey(help_text='فردی که این امتیاز را داده است (دانش\u200cآموز یا والدین)', on_delete=django.db.models.deletion.CASCADE, related_name='given_teacher_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Rater')),
                ('teacher', models.ForeignKey(help_text='معلمی که این امتیاز را دریافت کرده است', limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_teacher_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Teacher Rating',
                'verbose_name_plural': 'Teacher Ratings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['teacher', '-created_at'], name='account_tea_teacher_ffbc0d_idx'), models.Index(fields=['rater'], name='account_tea_rater_i_20da39_idx'), models.Index(fields=['rater_type'], name='account_tea_rater_t_6c67fa_idx')],
                'unique_together': {('teacher', 'rater')},
            },
        ),
    ]
