# Generated by Django 6.0 on 2026-01-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_teacherrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentappusagelog',
            name='last_reported_at',
            field=models.DateTimeField(blank=True, help_text='آخرین زمان گزارش مصرف از اپ', null=True, verbose_name='Last report at'),
        ),
        migrations.AddField(
            model_name='parentappusagelog',
            name='total_seconds',
            field=models.IntegerField(default=0, help_text='کل ثانیه\u200cهای استفاده در این روز', verbose_name='Total seconds used'),
        ),
    ]
