# Generated by Django 6.0 on 2026-05-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_parentappusagelog_last_reported_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherrating',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='آیا این امتیاز تایید شده است؟', verbose_name='Is Verified'),
        ),
    ]
