# Generated by Django 6.0.7 on 2026-07-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_teacherrating_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_score',
            field=models.IntegerField(default=0, verbose_name='Score'),
        ),
    ]
