# Generated by Django 6.0.7 on 2026-07-28 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_user_student_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='english_level',
            field=models.CharField(blank=True, choices=[('pre_a1', 'Pre-A1'), ('a1', 'A1 - Beginner'), ('a2', 'A2 - Elementary'), ('b1', 'B1 - Intermediate'), ('b2', 'B2 - Upper Intermediate'), ('c1', 'C1 - Advanced'), ('c2', 'C2 - Proficient')], db_index=True, max_length=10, null=True, verbose_name='سطح فعلی زبان انگلیسی'),
        ),
        migrations.AddField(
            model_name='user',
            name='english_level_assessed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessed_students', to=settings.AUTH_USER_MODEL, verbose_name='تعیین سطح شده توسط'),
        ),
        migrations.AddField(
            model_name='user',
            name='english_level_source',
            field=models.CharField(blank=True, choices=[('placement_test', 'Placement test'), ('admin', 'Admin assessment'), ('teacher', 'Teacher assessment'), ('imported', 'Imported')], max_length=30, null=True, verbose_name='منبع تعیین سطح'),
        ),
        migrations.AddField(
            model_name='user',
            name='english_level_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان آخرین تعیین سطح'),
        ),
    ]
