# Generated by Django 6.0.6 on 2026-06-10 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('classroom', '0020_withdrawalrequest_receipt_image'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='classenrollment',
            new_name='classes_cla_student_84f097_idx',
            old_name='classes_cla_student_b1a7ad_idx',
        ),
        migrations.RenameIndex(
            model_name='classenrollment',
            new_name='classes_cla_class_s_76ec50_idx',
            old_name='classes_cla_class_s_2adcf6_idx',
        ),
        migrations.RenameIndex(
            model_name='classmessage',
            new_name='classes_cla_class_s_402df0_idx',
            old_name='classes_cla_class_s_23eb30_idx',
        ),
        migrations.RenameIndex(
            model_name='classmessage',
            new_name='classes_cla_sender__00ef58_idx',
            old_name='classes_cla_sender__f83f35_idx',
        ),
        migrations.RenameIndex(
            model_name='classmessage',
            new_name='classes_cla_is_dele_2a7762_idx',
            old_name='classes_cla_is_dele_71dc86_idx',
        ),
        migrations.RenameIndex(
            model_name='classreaction',
            new_name='classes_cla_class_s_187d32_idx',
            old_name='classes_cla_class_s_81f18c_idx',
        ),
        migrations.RenameIndex(
            model_name='classreaction',
            new_name='classes_cla_student_26441d_idx',
            old_name='classes_cla_student_2ce8b1_idx',
        ),
        migrations.RenameIndex(
            model_name='handraise',
            new_name='classes_han_class_s_225c88_idx',
            old_name='classes_han_class_s_ba49dd_idx',
        ),
        migrations.RenameIndex(
            model_name='handraise',
            new_name='classes_han_student_ca0955_idx',
            old_name='classes_han_student_d39f2b_idx',
        ),
        migrations.RenameIndex(
            model_name='onlineclass',
            new_name='classes_onl_teacher_d0dec4_idx',
            old_name='classes_onl_teacher_183a48_idx',
        ),
        migrations.RenameIndex(
            model_name='onlineclass',
            new_name='classes_onl_schedul_3f3c22_idx',
            old_name='classes_onl_schedul_0b3097_idx',
        ),
        migrations.AddField(
            model_name='onlineclass',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booked_class', to='classroom.classbooking', verbose_name='کلاس رزرو شده'),
        ),
        migrations.AlterField(
            model_name='classenrollment',
            name='can_share_video',
            field=models.BooleanField(default=False, verbose_name='Can share video'),
        ),
    ]