# Generated by Django 6.0.7 on 2026-07-15 08:16

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_rename_classes_cla_student_b1a7ad_idx_classes_cla_student_84f097_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('file', models.FileField(upload_to=core.utils.upload_to_dynamic, verbose_name='File')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Original filename')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='File size (bytes)')),
                ('content_type', models.CharField(blank=True, max_length=150, verbose_name='Content type')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='classes.onlineclass', verbose_name='Class session')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_class_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_attachments_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded by')),
            ],
            options={
                'verbose_name': 'Class Attachment',
                'verbose_name_plural': 'Class Attachments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='classattachment',
            index=models.Index(fields=['class_session', 'created_at'], name='classes_cla_class_s_b5e9b3_idx'),
        ),
        migrations.AddIndex(
            model_name='classattachment',
            index=models.Index(fields=['is_deleted', 'created_at'], name='classes_cla_is_dele_52abbe_idx'),
        ),
    ]
