# Generated by Django 6.0.7 on 2026-07-28 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_classattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineclass',
            name='reward_granted',
            field=models.BooleanField(default=False, verbose_name='Reward granted'),
        ),
        migrations.AlterField(
            model_name='classmessage',
            name='class_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='classes.onlineclass', verbose_name='Class session'),
        ),
        migrations.AlterField(
            model_name='classmessage',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='classmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='classmessage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_class_messages', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AlterField(
            model_name='classmessage',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is deleted'),
        ),
        migrations.AlterField(
            model_name='classmessage',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Is private'),
        ),
        migrations.AlterField(
            model_name='classmessage',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_messages_received', to=settings.AUTH_USER_MODEL, verbose_name='Recipient'),
        ),
        migrations.AlterField(
            model_name='classmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_messages_sent', to=settings.AUTH_USER_MODEL, verbose_name='Sender'),
        ),
        migrations.AlterField(
            model_name='classreaction',
            name='class_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='classes.onlineclass', verbose_name='Class session'),
        ),
        migrations.AlterField(
            model_name='classreaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='classreaction',
            name='emoji',
            field=models.CharField(choices=[('👍', 'Thumbs Up'), ('❤️', 'Heart'), ('👏', 'Clap'), ('🎉', 'Party'), ('🤔', 'Thinking'), ('😮', 'Surprised')], max_length=10, verbose_name='Emoji'),
        ),
        migrations.AlterField(
            model_name='classreaction',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='classes.classmessage', verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='classreaction',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_reactions', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='handraise',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Acknowledged at'),
        ),
        migrations.AlterField(
            model_name='handraise',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_hands', to=settings.AUTH_USER_MODEL, verbose_name='Acknowledged by'),
        ),
        migrations.AlterField(
            model_name='handraise',
            name='class_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_hands', to='classes.onlineclass', verbose_name='Class session'),
        ),
        migrations.AlterField(
            model_name='handraise',
            name='lowered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lowered at'),
        ),
        migrations.AlterField(
            model_name='handraise',
            name='raised_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Raised at'),
        ),
        migrations.AlterField(
            model_name='handraise',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hand_raises', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
    ]
