# Generated by Django 6.0 on 2025-12-25 15:58

import ckeditor.fields
import core.utils
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('title_fa', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.utils.upload_to_dynamic, verbose_name='Image')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('content_fa', ckeditor.fields.RichTextField(null=True, verbose_name='Content')),
                ('content_en', ckeditor.fields.RichTextField(null=True, verbose_name='Content')),
            ],
            options={
                'verbose_name': 'About us',
                'verbose_name_plural': 'About us',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('title_fa', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('image', models.ImageField(upload_to=core.utils.upload_to_dynamic, verbose_name='Image')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Short description')),
                ('short_description_fa', models.TextField(blank=True, null=True, verbose_name='Short description')),
                ('short_description_en', models.TextField(blank=True, null=True, verbose_name='Short description')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('content_fa', ckeditor.fields.RichTextField(null=True, verbose_name='Content')),
                ('content_en', ckeditor.fields.RichTextField(null=True, verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('title_fa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('sub_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subtitle')),
                ('sub_title_fa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subtitle')),
                ('sub_title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subtitle')),
                ('image', models.ImageField(upload_to=core.utils.upload_to_dynamic, verbose_name='Image')),
                ('link', models.CharField(blank=True, help_text='Example: https://example.com', max_length=100, null=True, verbose_name='Link')),
                ('placement', models.CharField(choices=[('home', 'Home page'), ('app_home', 'App home')], default='home', max_length=50, verbose_name='Placement')),
                ('sort', models.IntegerField(default=0, verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('title_fa', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('link', models.CharField(blank=True, max_length=100, null=True, verbose_name='Link')),
                ('value', models.CharField(max_length=100, verbose_name='Value')),
                ('value_fa', models.CharField(max_length=100, null=True, verbose_name='Value')),
                ('value_en', models.CharField(max_length=100, null=True, verbose_name='Value')),
                ('type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'Notification number'), ('address', 'Address'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('youtube', 'YouTube'), ('spotify', 'Spotify')], default='phone', max_length=50, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Contact Method',
                'verbose_name_plural': 'Contact Methods',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR', verbose_name='Phone number')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contact message',
                'verbose_name_plural': 'Contact messages',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('question', models.CharField(max_length=100, verbose_name='Question')),
                ('question_fa', models.CharField(max_length=100, null=True, verbose_name='Question')),
                ('question_en', models.CharField(max_length=100, null=True, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('answer_fa', models.TextField(null=True, verbose_name='Answer')),
                ('answer_en', models.TextField(null=True, verbose_name='Answer')),
                ('is_active', models.BooleanField(default=True, verbose_name='Display status')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('title_fa', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('content_fa', ckeditor.fields.RichTextField(null=True, verbose_name='Content')),
                ('content_en', ckeditor.fields.RichTextField(null=True, verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policy',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('title_fa', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('content_fa', ckeditor.fields.RichTextField(null=True, verbose_name='Content')),
                ('content_en', ckeditor.fields.RichTextField(null=True, verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Terms & Conditions',
                'verbose_name_plural': 'Terms & Conditions',
            },
        ),
    ]
