# Generated by Django 6.0.4 on 2026-05-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoption',
            name='icon',
            field=models.CharField(blank=True, help_text='آیکون گزینه را وارد کنید', max_length=191, null=True, verbose_name='آیکون گزینه'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='icon',
            field=models.CharField(blank=True, help_text='آیکون سوال را وارد کنید', max_length=191, null=True, verbose_name='آیکون سوال'),
        ),
    ]
