# Generated by Django 6.0.4 on 2026-05-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_questionoption_icon_testquestion_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologicaltest',
            name='test_type',
            field=models.CharField(choices=[('register', 'Register'), ('regular', 'Regular')], default='regular', max_length=50, verbose_name='Type'),
        ),
    ]
