# Generated by Django 6.0.4 on 2026-05-09 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_psychologicaltest_test_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studenttestresponse',
            unique_together=set(),
        ),
    ]
