# Generated by Django 6.0 on 2025-12-30 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0006_classrevenue_notes_en_classrevenue_notes_fa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_fa', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('sort', models.BigIntegerField(default=0, verbose_name='Sort')),
                ('type', models.CharField(max_length=50, verbose_name='Type')),
                ('is_required', models.SmallIntegerField(blank=True, help_text='Is Required Help', null=True, verbose_name='Is Required')),
                ('image_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Image')),
                ('audio_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Audio')),
                ('video_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Video')),
                ('icon_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Icon')),
                ('guide', models.CharField(blank=True, max_length=255, null=True, verbose_name='Guide')),
                ('guide_fa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Guide')),
                ('guide_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Guide')),
                ('des', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('des_fa', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('des_en', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='CategoryField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('step', models.BigIntegerField(verbose_name='Step')),
                ('sort', models.BigIntegerField(verbose_name='Sort')),
                ('type', models.CharField(max_length=50, verbose_name='Type')),
                ('type_fa', models.CharField(max_length=50, null=True, verbose_name='Type')),
                ('type_en', models.CharField(max_length=50, null=True, verbose_name='Type')),
                ('is_conditional', models.BooleanField(default=False, verbose_name='Is Conditional')),
                ('teachingsubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_fields', to='classroom.teachingsubject', verbose_name='Classroom Teaching Subject')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_fields', to='exercise.field', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ['step', 'sort'],
            },
        ),
        migrations.CreateModel(
            name='FieldDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_fa', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('second_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Second Title')),
                ('second_title_fa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Second Title')),
                ('second_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Second Title')),
                ('is_required', models.SmallIntegerField(default=0, verbose_name='Is Required')),
                ('image_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Image')),
                ('is_correct', models.SmallIntegerField(default=-1, verbose_name='Is Correct')),
                ('guide', models.CharField(blank=True, max_length=255, null=True, verbose_name='Guide')),
                ('guide_fa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Guide')),
                ('guide_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Guide')),
                ('des', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('des_fa', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('des_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('sort', models.BigIntegerField(default=0, verbose_name='Sort')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='exercise.field', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
                ('correct', models.IntegerField(default=0, verbose_name='Correct')),
                ('incorrect', models.IntegerField(default=0, verbose_name='Incorrect')),
                ('teachingsubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='classroom.teachingsubject', verbose_name='Teaching Subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Attempt',
                'verbose_name_plural': 'Attempts',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Answer')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='exercise.field', verbose_name='Question')),
                ('field_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='exercise.fielddetail', verbose_name='Option')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='exercise.order', verbose_name='Answer')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
    ]
