# Generated by Django 6.0 on 2025-12-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='correct_answer',
            field=models.TextField(blank=True, help_text="For text/input questions - teacher's answer key for grading", null=True, verbose_name='Correct Answer'),
        ),
    ]
