# Generated by Django 6.0 on 2025-12-30 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_field_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='field_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='exercise.fielddetail', verbose_name='Option'),
        ),
    ]
