# Generated by Django 6.0 on 2025-12-31 15:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_supportmessage_supportmessageattachment_and_more'),
        ('exercise', '0003_alter_orderdetail_field_detail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMedal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('medal_type', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze'), ('star', 'Star'), ('heart', 'Heart'), ('trophy', 'Trophy'), ('certificate', 'Certificate'), ('badge', 'Badge'), ('achievement', 'Achievement'), ('custom', 'Custom')], default='gold', help_text='نوع مدال', max_length=20, verbose_name='Medal Type')),
                ('title', models.CharField(help_text='عنوان مدال (مثال: حل صحیح تمام سؤالات)', max_length=255, verbose_name='Medal Title')),
                ('description', models.TextField(blank=True, help_text='توضیح مدال', null=True, verbose_name='Description')),
                ('icon_url', models.CharField(blank=True, help_text='URL تصویر مدال', max_length=500, null=True, verbose_name='Icon URL')),
                ('order', models.ForeignKey(blank=True, help_text='تمرین یا آزمونی که این مدال برای آن است (اختیاری)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medals', to='exercise.order', verbose_name='Exercise/Attempt')),
                ('student', models.ForeignKey(help_text='دانش\u200cآموزی که مدال دریافت کرده است', limit_choices_to={'role': 'user'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_medals', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('teacher', models.ForeignKey(help_text='معلمی که این مدال را داده است', limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='given_medals', to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
                ('teachingsubject', models.ForeignKey(help_text='درسی که این مدال برای آن است', on_delete=django.db.models.deletion.CASCADE, related_name='student_medals', to='classroom.teachingsubject', verbose_name='Teaching Subject')),
            ],
            options={
                'verbose_name': 'Student Medal',
                'verbose_name_plural': 'Student Medals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', '-created_at'], name='exercise_st_student_49826d_idx'), models.Index(fields=['teacher'], name='exercise_st_teacher_dbf37f_idx'), models.Index(fields=['teachingsubject'], name='exercise_st_teachin_602787_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('rating_type', models.CharField(choices=[('exercise', 'Exercise'), ('activity', 'Class Activity'), ('participation', 'Participation'), ('behavior', 'Behavior'), ('other', 'Other')], default='exercise', help_text='نوع امتیازدهی', max_length=20, verbose_name='Rating Type')),
                ('score', models.IntegerField(default=0, help_text='امتیاز (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Score')),
                ('stars', models.IntegerField(default=0, help_text='ستاره (0-5)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Stars')),
                ('comment', models.TextField(blank=True, help_text='نظر معلم در مورد عملکرد دانش\u200cآموز', null=True, verbose_name='Comment')),
                ('order', models.OneToOneField(blank=True, help_text='تمرین یا آزمونی که این امتیاز برای آن است (اختیاری)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating', to='exercise.order', verbose_name='Exercise/Attempt')),
                ('student', models.ForeignKey(help_text='دانش\u200cآموزی که امتیاز دریافت کرده است', limit_choices_to={'role': 'user'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('teacher', models.ForeignKey(help_text='معلمی که این امتیاز را داده است', limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
                ('teachingsubject', models.ForeignKey(help_text='درسی که این امتیاز برای آن است', on_delete=django.db.models.deletion.CASCADE, related_name='student_ratings', to='classroom.teachingsubject', verbose_name='Teaching Subject')),
            ],
            options={
                'verbose_name': 'Student Rating',
                'verbose_name_plural': 'Student Ratings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', '-created_at'], name='exercise_st_student_b64f26_idx'), models.Index(fields=['teacher', '-created_at'], name='exercise_st_teacher_d8165a_idx'), models.Index(fields=['teachingsubject'], name='exercise_st_teachin_ef8544_idx')],
                'unique_together': {('student', 'order')},
            },
        ),
    ]
