# Generated by Django 6.0 on 2026-01-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_studentmedal_studentrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='fielddetail',
            name='correct_answer',
            field=models.TextField(blank=True, help_text="For text/input questions - teacher's answer key for grading", null=True, verbose_name='Correct Answer'),
        ),
    ]
