# Generated by Django 6.0 on 2026-01-02 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_remove_field_correct_answer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='teacher',
            field=models.ForeignKey(default=12, help_text='Teacher who created this question', limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_fields', to=settings.AUTH_USER_MODEL, verbose_name='Teacher'),
            preserve_default=False,
        ),
    ]
