# Generated by Django 6.0 on 2026-04-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_field_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('input', 'تایپی'), ('checkbox', 'چند گزینه ای'), ('radioButton', 'تک گزینه ای')], max_length=50, verbose_name='Type'),
        ),
    ]
