# Generated by Django 6.0 on 2026-04-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0007_alter_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfield',
            name='type',
            field=models.CharField(choices=[('input', 'تایپی'), ('checkbox', 'چند گزینه ای'), ('radioButton', 'تک گزینه ای')], max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='categoryfield',
            name='type_en',
            field=models.CharField(choices=[('input', 'تایپی'), ('checkbox', 'چند گزینه ای'), ('radioButton', 'تک گزینه ای')], max_length=50, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='categoryfield',
            name='type_fa',
            field=models.CharField(choices=[('input', 'تایپی'), ('checkbox', 'چند گزینه ای'), ('radioButton', 'تک گزینه ای')], max_length=50, null=True, verbose_name='Type'),
        ),
    ]
