# Generated by Django 6.0 on 2025-12-29 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacheravailability',
            options={'ordering': ['date', 'start_time'], 'verbose_name': 'زمان\u200cبندی کلاس معلم', 'verbose_name_plural': 'زمان\u200cبندی کلاس\u200cهای معلم'},
        ),
    ]
