# Generated by Django 6.0 on 2025-12-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_alter_teacheravailability_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheravailability',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='قیمت تدریس با تخفیف برای این بازه زمانی', max_digits=10, null=True, verbose_name='قیمت با تخفیف'),
        ),
        migrations.AlterField(
            model_name='teacheravailability',
            name='is_available',
            field=models.BooleanField(default=True, help_text='آیا این بازه زمانی برای رزرو دسترس\u200cپذیر است؟', verbose_name='دسترس\u200cپذیر'),
        ),
        migrations.AlterField(
            model_name='teacheravailability',
            name='is_booked',
            field=models.BooleanField(default=False, help_text='آیا این بازه زمانی قبلاً رزرو شده است؟', verbose_name='رزرو شده'),
        ),
        migrations.AlterField(
            model_name='teacheravailability',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='قیمت تدریس برای این بازه زمانی', max_digits=10, verbose_name='قیمت'),
        ),
    ]
