# Generated by Django 6.0 on 2025-12-29 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_teacheravailability_discount_price_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='discountcode',
            name='classroom_d_code_a4937e_idx',
        ),
        migrations.RemoveIndex(
            model_name='discountcode',
            name='classroom_d_is_acti_7ad34d_idx',
        ),
        migrations.RemoveField(
            model_name='classbooking',
            name='discount_code',
        ),
        migrations.RemoveField(
            model_name='classrevenue',
            name='notes_en',
        ),
        migrations.RemoveField(
            model_name='classrevenue',
            name='notes_fa',
        ),
        migrations.RemoveField(
            model_name='studenttransaction',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='studenttransaction',
            name='description_fa',
        ),
        migrations.RemoveField(
            model_name='teacheravailability',
            name='notes_en',
        ),
        migrations.RemoveField(
            model_name='teacheravailability',
            name='notes_fa',
        ),
        migrations.RemoveField(
            model_name='teachingsubject',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='teachingsubject',
            name='description_fa',
        ),
        migrations.RemoveField(
            model_name='teachingsubject',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='teachingsubject',
            name='title_fa',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='admin_note_en',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='admin_note_fa',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='description_fa',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='admin_notes_en',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='admin_notes_fa',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='notes_en',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='notes_fa',
        ),
        migrations.DeleteModel(
            name='DiscountCode',
        ),
    ]
