# Generated by Django 6.0 on 2025-12-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_remove_discountcode_classroom_d_code_a4937e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheravailability',
            name='is_available',
            field=models.BooleanField(default=True, help_text='آیا این بازه زمانی برای رزرو در دسترس است؟', verbose_name='در دسترس'),
        ),
    ]
