# Generated by Django 6.0 on 2025-12-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_alter_teacheravailability_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrevenue',
            name='notes_en',
            field=models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها'),
        ),
        migrations.AddField(
            model_name='classrevenue',
            name='notes_fa',
            field=models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها'),
        ),
        migrations.AddField(
            model_name='studenttransaction',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح'),
        ),
        migrations.AddField(
            model_name='studenttransaction',
            name='description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح'),
        ),
        migrations.AddField(
            model_name='teacheravailability',
            name='notes_en',
            field=models.TextField(blank=True, help_text='یادداشت\u200cهای اضافی درباره این دسترسی', null=True, verbose_name='یادداشت\u200cها'),
        ),
        migrations.AddField(
            model_name='teacheravailability',
            name='notes_fa',
            field=models.TextField(blank=True, help_text='یادداشت\u200cهای اضافی درباره این دسترسی', null=True, verbose_name='یادداشت\u200cها'),
        ),
        migrations.AddField(
            model_name='teachingsubject',
            name='description_en',
            field=models.TextField(help_text='توضیح در مورد آنچه در این درس تدریس خواهد شد', null=True, verbose_name='توضیح'),
        ),
        migrations.AddField(
            model_name='teachingsubject',
            name='description_fa',
            field=models.TextField(help_text='توضیح در مورد آنچه در این درس تدریس خواهد شد', null=True, verbose_name='توضیح'),
        ),
        migrations.AddField(
            model_name='teachingsubject',
            name='title_en',
            field=models.CharField(help_text='مثال: انگلیسی مبتدی - الفبا', max_length=200, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='teachingsubject',
            name='title_fa',
            field=models.CharField(help_text='مثال: انگلیسی مبتدی - الفبا', max_length=200, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='admin_note_en',
            field=models.TextField(blank=True, null=True, verbose_name='یادداشت ادمین'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='admin_note_fa',
            field=models.TextField(blank=True, null=True, verbose_name='یادداشت ادمین'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='admin_notes_en',
            field=models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cهای ادمین'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='admin_notes_fa',
            field=models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cهای ادمین'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='notes_en',
            field=models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='notes_fa',
            field=models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها'),
        ),
    ]
