# Generated by Django 6.0 on 2025-12-30 09:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_classrevenue_notes_en_classrevenue_notes_fa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheravailability',
            name='is_expired',
            field=models.BooleanField(default=False, help_text='آیا این بازه زمانی منقضی شده است؟', verbose_name='منقضی شده'),
        ),
        migrations.AddIndex(
            model_name='teacheravailability',
            index=models.Index(fields=['is_expired'], name='classroom_t_is_expi_26180d_idx'),
        ),
    ]
