# Generated by Django 6.0 on 2025-12-30 11:45

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_teacheravailability_is_expired_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingsubject',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.upload_to_dynamic, verbose_name='عکس کاور'),
        ),
        migrations.AlterField(
            model_name='teachingsubject',
            name='demo_video',
            field=models.FileField(blank=True, help_text='ویدیوی نمونه کوتاه تدریس (MP4, WebM, etc)', null=True, upload_to=core.utils.upload_to_dynamic, verbose_name='ویدیوی نمونه'),
        ),
    ]
