# Generated by Django 6.0 on 2025-12-30 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_alter_teachingsubject_cover_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غایب')], max_length=10, verbose_name='وضعیت')),
                ('marked_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ثبت')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='classroom.classbooking', verbose_name='رزرو کلاس')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'user'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'حضور و غیاب',
                'verbose_name_plural': 'حضور و غیاب',
                'indexes': [models.Index(fields=['student', 'marked_at'], name='classroom_a_student_826e64_idx'), models.Index(fields=['booking', 'student'], name='classroom_a_booking_03c2fa_idx')],
                'unique_together': {('booking', 'student')},
            },
        ),
    ]
