# Generated by Django 6.0 on 2025-12-30 17:39

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('message_text', models.TextField(blank=True, help_text='متن پیام', null=True, verbose_name='Message text')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('read', 'Read')], default='sent', help_text='وضعیت پیام', max_length=10, verbose_name='Status')),
                ('read_at', models.DateTimeField(blank=True, help_text='زمان خواندن پیام', null=True, verbose_name='Read at')),
                ('sender', models.ForeignKey(blank=True, help_text='فردی که پیام را فرستاد (معلم یا پشتیبان)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_support_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
                ('teacher', models.ForeignKey(help_text='معلمی که پیام را ارسال کرد', limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Support Message',
                'verbose_name_plural': 'Support Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('file', models.FileField(help_text='فایل پیوست (عکس، PDF، صدا، و غیره)', upload_to=core.utils.upload_to_dynamic, verbose_name='Attachment file')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='classroom.supportmessage', verbose_name='Support Message')),
            ],
            options={
                'verbose_name': 'Support Message Attachment',
                'verbose_name_plural': 'Support Message Attachments',
            },
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['teacher', '-created_at'], name='classroom_s_teacher_ca2f40_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['status', '-created_at'], name='classroom_s_status_f91b50_idx'),
        ),
    ]
