# Generated by Django 6.0 on 2026-01-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_supportmessage_supportmessageattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classbooking',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ پرداختی'),
        ),
        migrations.AddField(
            model_name='classbooking',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AddField(
            model_name='classbooking',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شناسه تراکنش'),
        ),
        migrations.AddField(
            model_name='classbooking',
            name='payment_status',
            field=models.CharField(choices=[('not_paid', 'پرداخت نشده'), ('partial', 'جزئی'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق')], default='not_paid', max_length=20, verbose_name='وضعیت پرداخت'),
        ),
    ]
