# Generated by Django 6.0 on 2026-01-01 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_classbooking_paid_amount_classbooking_paid_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttransaction',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'user'}, on_delete=django.db.models.deletion.CASCADE, related_name='class_transactions', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز'),
        ),
    ]
