# Generated by Django 6.0 on 2026-01-06 13:00

import core.utils
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_alter_studenttransaction_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('title', models.CharField(help_text='نام پکیج آموزشی (مثال: انگلیسی مبتدی - ۳۰ جلسه)', max_length=200, verbose_name='نام پکیج')),
                ('description', models.TextField(blank=True, help_text='توضیح تفصیلی درباره محتوای پکیج', verbose_name='توضیح پکیج')),
                ('cover_image', models.ImageField(blank=True, help_text='تصویر کاور برای نمایش در فروشگاه', null=True, upload_to=core.utils.upload_to_dynamic, verbose_name='تصویر پکیج')),
                ('total_sessions', models.PositiveIntegerField(help_text='کل تعداد جلسات در این پکیج', validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد کل جلسات')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='قیمت کل پکیج (جمع همه اقساط)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت کل پکیج')),
                ('has_installment', models.BooleanField(default=False, help_text='آیا معلم قسط\u200cبندی برای این پکیج تعریف کرده؟', verbose_name='قسط\u200cبندی تعریف\u200cشده')),
                ('is_active', models.BooleanField(default=True, help_text='آیا این پکیج برای فروش فعال است؟', verbose_name='فعال')),
                ('subjects', models.ManyToManyField(help_text='یک یا چند موضوع تدریس که این پکیج شامل آن است', related_name='packages', to='classroom.teachingsubject', verbose_name='موضوعات')),
                ('teacher', models.ForeignKey(help_text='معلمی که این پکیج را تعریف کرده', limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL, verbose_name='معلم')),
            ],
            options={
                'verbose_name': 'پکیج آموزشی',
                'verbose_name_plural': 'پکیج\u200cهای آموزشی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('installment_number', models.PositiveIntegerField(help_text='ترتیب قسط (1، 2، 3، ...)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='شماره قسط')),
                ('amount', models.DecimalField(decimal_places=2, help_text='مبلغ این قسط به تومان', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ قسط')),
                ('session_number', models.PositiveIntegerField(help_text='قسط باید قبل از شروع این جلسه پرداخت شود', verbose_name='شماره جلسه')),
                ('description', models.TextField(blank=True, help_text='توضیح اضافی درباره این قسط', verbose_name='توضیح')),
                ('package', models.ForeignKey(help_text='پکیجی که این قسط متعلق به آن است', on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='classroom.package', verbose_name='پکیج')),
            ],
            options={
                'verbose_name': 'قسط پکیج',
                'verbose_name_plural': 'اقساط پکیج',
                'ordering': ['package', 'installment_number'],
            },
        ),
        migrations.CreateModel(
            name='StudentPackageEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ثبت\u200cنام دانش\u200cآموز', verbose_name='تاریخ ثبت\u200cنام')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('completed', 'تکمیل\u200cشده'), ('cancelled', 'لغو\u200cشده'), ('suspended', 'تعلیق\u200cشده')], default='active', help_text='وضعیت فعلی ثبت\u200cنام', max_length=20, verbose_name='وضعیت')),
                ('completed_sessions_count', models.PositiveIntegerField(default=0, help_text='تعداد جلسات\u200cای که دانش\u200cآموز حضور داشته است', verbose_name='تعداد جلسات تکمیل\u200cشده')),
                ('notes', models.TextField(blank=True, help_text='یادداشت\u200cهای اضافی درباره ثبت\u200cنام', verbose_name='یادداشت\u200cها')),
                ('package', models.ForeignKey(help_text='پکیج آموزشی', on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='classroom.package', verbose_name='پکیج')),
                ('student', models.ForeignKey(help_text='دانش\u200cآموزی که برای پکیج ثبت\u200cنام کرد', limit_choices_to={'role': 'user'}, on_delete=django.db.models.deletion.CASCADE, related_name='package_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام دانش\u200cآموز به پکیج',
                'verbose_name_plural': 'ثبت\u200cنام\u200cهای دانش\u200cآموزان به پکیج\u200cها',
                'ordering': ['-enrollment_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentPackagePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('amount_due', models.DecimalField(decimal_places=2, help_text='مبلغ مقرر برای این قسط', max_digits=12, verbose_name='مبلغ مقرر')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='مبلغ پرداخت\u200cشده (ممکن است جزئی باشد)', max_digits=12, verbose_name='مبلغ پرداختی')),
                ('payment_status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('partial', 'جزئی'), ('paid', 'پرداخت\u200cشده'), ('failed', 'ناموفق'), ('refunded', 'بازگشت\u200cشده')], default='pending', help_text='وضعیت فعلی پرداخت', max_length=20, verbose_name='وضعیت پرداخت')),
                ('payment_ref', models.CharField(blank=True, help_text='شناسه تراکنش درگاه پرداخت', max_length=255, null=True, verbose_name='شناسه تراکنش')),
                ('first_payment_date', models.DateTimeField(blank=True, help_text='تاریخ اولین پرداخت برای این قسط', null=True, verbose_name='تاریخ اولین پرداخت')),
                ('last_payment_date', models.DateTimeField(blank=True, help_text='تاریخ آخرین پرداخت برای این قسط', null=True, verbose_name='تاریخ آخرین پرداخت')),
                ('completed_date', models.DateTimeField(blank=True, help_text='تاریخ تکمیل پرداخت (زمانی که مبلغ کامل پرداخت شود)', null=True, verbose_name='تاریخ تکمیل')),
                ('notes', models.TextField(blank=True, help_text='یادداشت\u200cهای اضافی درباره پرداخت', verbose_name='یادداشت\u200cها')),
                ('enrollment', models.ForeignKey(help_text='ثبت\u200cنام دانش\u200cآموز به پکیج', on_delete=django.db.models.deletion.CASCADE, related_name='installment_payments', to='classroom.studentpackageenrollment', verbose_name='ثبت\u200cنام')),
                ('installment', models.ForeignKey(help_text='قسطی که پرداخت برای آن است', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='classroom.packageinstallment', verbose_name='قسط')),
            ],
            options={
                'verbose_name': 'پرداخت قسط پکیج',
                'verbose_name_plural': 'پرداخت\u200cهای قسط\u200cهای پکیج',
                'ordering': ['enrollment', 'installment__installment_number'],
            },
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['teacher', 'is_active'], name='classroom_p_teacher_c62c88_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['is_active', '-created_at'], name='classroom_p_is_acti_e60457_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['teacher', '-created_at'], name='classroom_p_teacher_ece510_idx'),
        ),
        migrations.AddIndex(
            model_name='packageinstallment',
            index=models.Index(fields=['package', 'installment_number'], name='classroom_p_package_f032d5_idx'),
        ),
        migrations.AddIndex(
            model_name='packageinstallment',
            index=models.Index(fields=['package', 'session_number'], name='classroom_p_package_91bf0f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='packageinstallment',
            unique_together={('package', 'installment_number'), ('package', 'session_number')},
        ),
        migrations.AddIndex(
            model_name='studentpackageenrollment',
            index=models.Index(fields=['student', 'status'], name='classroom_s_student_eb09e4_idx'),
        ),
        migrations.AddIndex(
            model_name='studentpackageenrollment',
            index=models.Index(fields=['package', 'status'], name='classroom_s_package_2a2358_idx'),
        ),
        migrations.AddIndex(
            model_name='studentpackageenrollment',
            index=models.Index(fields=['status', '-enrollment_date'], name='classroom_s_status_c5aefb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentpackageenrollment',
            unique_together={('student', 'package')},
        ),
        migrations.AddIndex(
            model_name='studentpackagepayment',
            index=models.Index(fields=['enrollment', 'payment_status'], name='classroom_s_enrollm_4d855f_idx'),
        ),
        migrations.AddIndex(
            model_name='studentpackagepayment',
            index=models.Index(fields=['installment', 'payment_status'], name='classroom_s_install_a80ed6_idx'),
        ),
        migrations.AddIndex(
            model_name='studentpackagepayment',
            index=models.Index(fields=['payment_status', '-last_payment_date'], name='classroom_s_payment_d1a2ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentpackagepayment',
            unique_together={('enrollment', 'installment')},
        ),
    ]
