# Generated by Django 6.0 on 2026-01-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_alter_package_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='subjects',
            field=models.ManyToManyField(help_text='یک یا چند موضوع تدریس که این پکیج شامل آن است', related_name='packages', to='classroom.teachingsubject', verbose_name='موضوعات'),
        ),
    ]
