# Generated by Django 6.0 on 2026-04-12 11:15

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0016_course_courseenrollment_classbooking_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.upload_to_dynamic, verbose_name='عکس کاور'),
        ),
    ]
