# Generated by Django 6.0 on 2026-04-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0017_course_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingsubject',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='در صورت رد، دلیل را وارد کنید', null=True, verbose_name='دلیل رد'),
        ),
        migrations.AddField(
            model_name='teachingsubject',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت تایید'),
        ),
    ]
