# Generated by Django 6.0 on 2026-05-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0019_course_rejection_reason_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='withdrawal_receipts/%Y/%m/', verbose_name='فیش واریزی'),
        ),
    ]
