# Generated by Django 6.0.7 on 2026-07-28 09:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخرین تغییر')),
                ('code', models.SlugField(unique=True, verbose_name='کد سطح')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان سطح')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('audience', models.CharField(choices=[('child', 'کودک'), ('teen', 'نوجوان'), ('adult', 'بزرگسال')], default='child', max_length=10, verbose_name='گروه سنی')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=1, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'سطح بازی',
                'verbose_name_plural': 'سطح\u200cهای بازی',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WordTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخرین تغییر')),
                ('code', models.SlugField(unique=True, verbose_name='کد موضوع')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان موضوع')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'موضوع کلمه',
                'verbose_name_plural': 'موضوعات کلمات',
                'ordering': ['order', 'title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GameStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخرین تغییر')),
                ('code', models.SlugField(max_length=70, unique=True, verbose_name='کد مرحله')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان مرحله')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='ترتیب در سطح')),
                ('min_difficulty', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='حداقل سختی')),
                ('max_difficulty', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='حداکثر سختی')),
                ('pairs_per_round', models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(12)], verbose_name='تعداد جفت در هر دور')),
                ('rounds_to_unlock', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='تعداد دور موفق برای عبور')),
                ('max_mistakes', models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='حداکثر اشتباه برای ثبت دور موفق')),
                ('time_limit_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='محدودیت زمانی به ثانیه')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='luna_game.gamelevel', verbose_name='سطح')),
            ],
            options={
                'verbose_name': 'مرحله بازی',
                'verbose_name_plural': 'مرحله\u200cهای بازی',
                'ordering': ['level__order', 'order', 'id'],
                'indexes': [models.Index(fields=['level', 'is_active', 'order'], name='luna_stage_level_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('min_difficulty__lte', models.F('max_difficulty'))), name='luna_stage_valid_difficulty_range')],
            },
        ),
        migrations.CreateModel(
            name='WordPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخرین تغییر')),
                ('en', models.CharField(max_length=150, verbose_name='کلمه انگلیسی')),
                ('fa', models.CharField(max_length=150, verbose_name='معنی فارسی')),
                ('difficulty', models.PositiveSmallIntegerField(db_index=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='درجه سختی')),
                ('admin_note', models.CharField(blank=True, max_length=255, verbose_name='یادداشت ادمین')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='word_pairs', to='luna_game.gamelevel', verbose_name='سطح')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='word_pairs', to='luna_game.wordtopic', verbose_name='موضوع')),
            ],
            options={
                'verbose_name': 'جفت کلمه',
                'verbose_name_plural': 'جفت\u200cهای کلمه',
                'ordering': ['level__order', 'difficulty', 'id'],
                'indexes': [models.Index(fields=['level', 'is_active', 'difficulty'], name='luna_word_level_diff_idx'), models.Index(fields=['topic', 'is_active'], name='luna_word_topic_idx')],
                'constraints': [models.UniqueConstraint(fields=('level', 'en', 'fa'), name='luna_unique_pair_per_level')],
            },
        ),
    ]
