# Generated by Django 6.0.4 on 2026-04-22 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologicalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('title', models.CharField(help_text='مثال: تست مهاجرت تحصیلی', max_length=255, verbose_name='عنوان تست')),
                ('title_fa', models.CharField(help_text='مثال: تست مهاجرت تحصیلی', max_length=255, null=True, verbose_name='عنوان تست')),
                ('title_en', models.CharField(help_text='مثال: تست مهاجرت تحصیلی', max_length=255, null=True, verbose_name='عنوان تست')),
                ('description', models.TextField(blank=True, help_text='توضیحات کلی درباره تست', verbose_name='توضیحات')),
                ('description_fa', models.TextField(blank=True, help_text='توضیحات کلی درباره تست', null=True, verbose_name='توضیحات')),
                ('description_en', models.TextField(blank=True, help_text='توضیحات کلی درباره تست', null=True, verbose_name='توضیحات')),
                ('description_ar', models.TextField(blank=True, help_text='توضیحات کلی درباره تست', null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'تست راهنمای مهاجرت',
                'verbose_name_plural': 'Immigration Guide Tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentTestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('not_started', 'شروع نشده'), ('in_progress', 'در حال پاسخ'), ('completed', 'تکمیل شده')], default='not_started', max_length=20, verbose_name='وضعیت')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_responses', to='recommendation.psychologicaltest', verbose_name='تست')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_responses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پاسخ کاربر',
                'verbose_name_plural': 'پاسخ\u200cهای کاربران',
                'ordering': ['-completed_at'],
                'unique_together': {('test', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('question_text', models.TextField(help_text='سوال مورد نظر را وارد کنید', verbose_name='متن سوال')),
                ('question_text_fa', models.TextField(help_text='سوال مورد نظر را وارد کنید', null=True, verbose_name='متن سوال')),
                ('question_text_en', models.TextField(help_text='سوال مورد نظر را وارد کنید', null=True, verbose_name='متن سوال')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'چند گزینه\u200cای')], default='multiple_choice', max_length=20, verbose_name='نوع سوال')),
                ('order', models.PositiveIntegerField(default=0, help_text='ترتیب نمایش سوال در تست', verbose_name='ترتیب')),
                ('is_required', models.BooleanField(default=True, help_text='آیا پاسخ به این سوال اجباری است؟', verbose_name='اجباری')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='recommendation.psychologicaltest', verbose_name='تست')),
            ],
            options={
                'verbose_name': 'سوال تست',
                'verbose_name_plural': 'سوالات تست',
                'ordering': ['test', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('option_text', models.CharField(max_length=255, verbose_name='متن گزینه')),
                ('option_text_fa', models.CharField(max_length=255, null=True, verbose_name='متن گزینه')),
                ('option_text_en', models.CharField(max_length=255, null=True, verbose_name='متن گزینه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='recommendation.testquestion', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'گزینه سوال',
                'verbose_name_plural': 'گزینه\u200cهای سوال',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ محاسبه')),
                ('raw_scores', models.JSONField(help_text='امتیاز هر مقیاس به صورت دیکشنری', verbose_name='امتیازات خام')),
                ('summary', models.JSONField(help_text='کد نهایی و اطلاعات خلاصه', verbose_name='خلاصه نتیجه')),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='recommendation.studenttestresponse', verbose_name='پاسخ دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'نتیجه آزمون',
                'verbose_name_plural': 'نتایج آزمون\u200cها',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='TestScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('code', models.CharField(help_text='مثال: R, I, A, S, E, C', max_length=20, verbose_name='کد مقیاس')),
                ('title', models.CharField(help_text='مثال: واقع\u200cگرا، پژوهشگر', max_length=255, verbose_name='عنوان مقیاس')),
                ('title_fa', models.CharField(help_text='مثال: واقع\u200cگرا، پژوهشگر', max_length=255, null=True, verbose_name='عنوان مقیاس')),
                ('title_en', models.CharField(help_text='مثال: واقع\u200cگرا، پژوهشگر', max_length=255, null=True, verbose_name='عنوان مقیاس')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('description_fa', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scales', to='recommendation.psychologicaltest', verbose_name='تست')),
            ],
            options={
                'verbose_name': 'مقیاس تست',
                'verbose_name_plural': 'مقیاس\u200cهای تست',
                'ordering': ['test', 'code'],
                'unique_together': {('test', 'code')},
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('text_answer', models.TextField(blank=True, verbose_name='پاسخ متنی')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان پاسخ')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_answers', to='recommendation.questionoption', verbose_name='گزینه انتخابی')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='recommendation.studenttestresponse', verbose_name='پاسخ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='recommendation.testquestion', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'پاسخ به سوال',
                'verbose_name_plural': 'پاسخ\u200cها به سوالات',
                'ordering': ['question__order'],
                'unique_together': {('response', 'question')},
            },
        ),
        migrations.CreateModel(
            name='ScaleInterpretation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('min_score', models.FloatField(help_text='امتیاز شروع بازه', verbose_name='حداقل امتیاز')),
                ('max_score', models.FloatField(help_text='امتیاز پایان بازه', verbose_name='حداکثر امتیاز')),
                ('title', models.CharField(help_text='مثال: رغبت بالا، رغبت متوسط', max_length=255, verbose_name='عنوان تفسیر')),
                ('title_fa', models.CharField(help_text='مثال: رغبت بالا، رغبت متوسط', max_length=255, null=True, verbose_name='عنوان تفسیر')),
                ('title_en', models.CharField(help_text='مثال: رغبت بالا، رغبت متوسط', max_length=255, null=True, verbose_name='عنوان تفسیر')),
                ('description', models.TextField(help_text='تفسیر روانشناختی کامل', verbose_name='توضیحات تفسیر')),
                ('description_fa', models.TextField(help_text='تفسیر روانشناختی کامل', null=True, verbose_name='توضیحات تفسیر')),
                ('description_en', models.TextField(help_text='تفسیر روانشناختی کامل', null=True, verbose_name='توضیحات تفسیر')),
                ('description_ar', models.TextField(help_text='تفسیر روانشناختی کامل', null=True, verbose_name='توضیحات تفسیر')),
                ('order', models.PositiveIntegerField(default=0, help_text='ترتیب نمایش تفسیر', verbose_name='ترتیب')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interpretations', to='recommendation.testscale', verbose_name='مقیاس')),
            ],
            options={
                'verbose_name': 'تفسیر مقیاس',
                'verbose_name_plural': 'تفسیرهای مقیاس\u200cها',
                'ordering': ['scale', 'order', 'min_score'],
                'unique_together': {('scale', 'min_score', 'max_score')},
            },
        ),
        migrations.CreateModel(
            name='OptionScaleWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('weight', models.FloatField(help_text='مثال: 1 ، 0.5 ، -1', verbose_name='وزن')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scale_weights', to='recommendation.questionoption', verbose_name='گزینه')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_weights', to='recommendation.testscale', verbose_name='مقیاس')),
            ],
            options={
                'verbose_name': 'وزن گزینه برای مقیاس',
                'verbose_name_plural': 'وزن\u200cهای گزینه\u200cها برای مقیاس\u200cها',
                'ordering': ['scale', 'option'],
                'unique_together': {('option', 'scale')},
            },
        ),
    ]
