# Generated by Django 6.0.4 on 2026-05-09 06:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0004_alter_studenttestresponse_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studenttestresponse',
            unique_together={('test', 'user')},
        ),
    ]
