# Generated by Django 6.0.7 on 2026-07-28 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0005_alter_studenttestresponse_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychologicaltest',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='psychologicaltest',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='option_text_ar',
        ),
        migrations.RemoveField(
            model_name='scaleinterpretation',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='scaleinterpretation',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='question_text_ar',
        ),
        migrations.RemoveField(
            model_name='testscale',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='testscale',
            name='title_ar',
        ),
    ]
