# Generated by Django 6.0.7 on 2026-07-28 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0005_alter_studenttestresponse_unique_together'),
    ]

    operations = [
        
    ]
